version: '3.5'
services:
  torchserve:
    image: torchserve
    build: .
    ports:
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
    command: torchserve --start --ncs --model-store ./serve/model_store --models ./serve/model_store/ocr_model.mar --foreground --ts-config ./serve/config.properties
  streamlit:
    image: streamlit
    ports: 
      - "8501:8501"
    command: streamlit run app.py